import Head from "next/head";
import Best from "../components/landing/Best";
import Brand from "../components/Brand";
import Choose from "../components/landing/Choose";
import Doctors from "../components/Doctors";
import Faq from "../components/landing/Faq";
import Happy from "../components/Happy";
import LandingHero from "../components/landing/LandingHero";
import Pride from "../components/Pride";
import Product from "../components/Product";
import Steps from "../components/Steps";
import Work from "../components/landing/Work";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingHero />
      <Best />
      <Work />
      <Steps />
      <Pride />
      <Doctors />
      <Choose />
      <Faq />
      <Brand />
      <Product />
      <Happy />
    </div>
  );
}
